---
resources:
- name: src
  type: git
  check_every: 1m
  source:
    uri: https://github.com/jprelph/concourse-demos.git
    branch: main
- name: test-image
  type: registry-image
  source:
    repository: jprelph/test-image
    tag: latest
    username: jprelph
    password: ((docker_password))

jobs:
- name: create-image
  plan:
    - get: src
      trigger: true
    - put: test-image
      params:
        image: image/image.tar
    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
        params:
          DOCKERFILE: src/Dockerfile
        inputs:
        - name: src
        outputs:
        - name: image
        run:
          path: build
